
#undef ROCKHOPPER_LOG_FATAL
#define ROCKHOPPER_LOG_FATAL(...)

#undef ROCKHOPPER_LOG_ERROR
#define ROCKHOPPER_LOG_ERROR(...)

#undef ROCKHOPPER_LOG_WARN
#define ROCKHOPPER_LOG_WARN(...)

#undef ROCKHOPPER_LOG_INFO
#define ROCKHOPPER_LOG_INFO(...)

#undef ROCKHOPPER_LOG_DEBUG
#define ROCKHOPPER_LOG_DEBUG(...)

#undef ROCKHOPPER_LOG_TRACE
#define ROCKHOPPER_LOG_TRACE(...)
